language: php
dist: trusty
php:
  # - '5.4'
  # - '5.5'
  # - '5.6'
  # - '7.0'
  # - '7.1'
  # - hhvm
  - nightly
script: ./run.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: output
  repo: chumanfu/chumanfu.github.io
  target_branch: master